// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-UZbXCUYzYOHse5O8Xk8s8elyeB8_6lQ',
    appId: '1:188631012849:web:04b9adbf7272563c7e2050',
    messagingSenderId: '188631012849',
    projectId: 'go-med-9a330',
    authDomain: 'go-med-9a330.firebaseapp.com',
    databaseURL: 'https://go-med-9a330-default-rtdb.firebaseio.com',
    storageBucket: 'go-med-9a330.firebasestorage.app',
    measurementId: 'G-H37JY7TBH9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2af-NHCkHX6LDtfzOYR4gea6xFFOAx1o',
    appId: '1:188631012849:android:73ef8e78320e12627e2050',
    messagingSenderId: '188631012849',
    projectId: 'go-med-9a330',
    databaseURL: 'https://go-med-9a330-default-rtdb.firebaseio.com',
    storageBucket: 'go-med-9a330.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRo84aNwN8rfejDKGdZnj9JW9RDToDQo0',
    appId: '1:188631012849:ios:98343e8af18969297e2050',
    messagingSenderId: '188631012849',
    projectId: 'go-med-9a330',
    databaseURL: 'https://go-med-9a330-default-rtdb.firebaseio.com',
    storageBucket: 'go-med-9a330.firebasestorage.app',
    iosBundleId: 'com.example.gomeduser.gomedUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRo84aNwN8rfejDKGdZnj9JW9RDToDQo0',
    appId: '1:188631012849:ios:98343e8af18969297e2050',
    messagingSenderId: '188631012849',
    projectId: 'go-med-9a330',
    databaseURL: 'https://go-med-9a330-default-rtdb.firebaseio.com',
    storageBucket: 'go-med-9a330.firebasestorage.app',
    iosBundleId: 'com.example.gomeduser.gomedUser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-UZbXCUYzYOHse5O8Xk8s8elyeB8_6lQ',
    appId: '1:188631012849:web:eca97f41bc39dfa37e2050',
    messagingSenderId: '188631012849',
    projectId: 'go-med-9a330',
    authDomain: 'go-med-9a330.firebaseapp.com',
    databaseURL: 'https://go-med-9a330-default-rtdb.firebaseio.com',
    storageBucket: 'go-med-9a330.firebasestorage.app',
    measurementId: 'G-SQBB199CP6',
  );

}