// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDsnIu_TrR3VnGcu3DQLZCOjprsV7VqhA',
    appId: '1:942219741281:web:98f68c57cb114357624220',
    messagingSenderId: '942219741281',
    projectId: 'go-med-serve',
    authDomain: 'go-med-serve.firebaseapp.com',
    storageBucket: 'go-med-serve.firebasestorage.app',
    measurementId: 'G-2T02FSJBXQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCQI-bNCFSenC7rsyc8NHZVxtoUfSH1O8',
    appId: '1:942219741281:android:80f8da2ecb63c1b1624220',
    messagingSenderId: '942219741281',
    projectId: 'go-med-serve',
    storageBucket: 'go-med-serve.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCoPoASlRloT-sHluzDk1xMn8iJeZLD6c',
    appId: '1:942219741281:ios:11622e03ddc4fa03624220',
    messagingSenderId: '942219741281',
    projectId: 'go-med-serve',
    storageBucket: 'go-med-serve.firebasestorage.app',
    iosBundleId: 'gomeduser.gomedUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCoPoASlRloT-sHluzDk1xMn8iJeZLD6c',
    appId: '1:942219741281:ios:11622e03ddc4fa03624220',
    messagingSenderId: '942219741281',
    projectId: 'go-med-serve',
    storageBucket: 'go-med-serve.firebasestorage.app',
    iosBundleId: 'gomeduser.gomedUser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDsnIu_TrR3VnGcu3DQLZCOjprsV7VqhA',
    appId: '1:942219741281:web:e2d461d1a5d4f10e624220',
    messagingSenderId: '942219741281',
    projectId: 'go-med-serve',
    authDomain: 'go-med-serve.firebaseapp.com',
    storageBucket: 'go-med-serve.firebasestorage.app',
    measurementId: 'G-Z5HD82DNKV',
  );
}
